"""initial schema

Revision ID: 78daee919109
Revises: 
Create Date: 2026-09-11 01:08:35.068915
"""
from alembic import op
import sqlalchemy as sa


revision = '78daee919109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_sha256'), ['sha256'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('netid', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('platform_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_netid'), ['netid'], unique=True)

    op.create_table('device_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_code', sa.String(length=16), nullable=False),
    sa.Column('client', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code_hash')
    )
    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_codes_user_code'), ['user_code'], unique=True)

    op.create_table('offerings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'term', name='uq_offering_course_term')
    )
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offerings_course_id'), ['course_id'], unique=False)

    op.create_table('web_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('saml_name_id', sa.String(length=300), nullable=True),
    sa.Column('saml_session_index', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'slug', name='uq_assignment_slug')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_offering_id'), ['offering_id'], unique=False)

    op.create_table('grade_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('offering_id', sa.Uuid(), nullable=True),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_audit_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grade_audit_offering_id'), ['offering_id'], unique=False)

    op.create_table('roster_uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roster_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roster_uploads_offering_id'), ['offering_id'], unique=False)

    op.create_table('rubrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rubrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubrics_offering_id'), ['offering_id'], unique=False)

    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'name', name='uq_section_name')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_offering_id'), ['offering_id'], unique=False)

    op.create_table('assignment_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('instructor_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('student_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('cell_hashes', sa.JSON(), nullable=False),
    sa.Column('question_snapshot', sa.JSON(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['instructor_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'version', name='uq_version')
    )
    with op.batch_alter_table('assignment_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_versions_assignment_id'), ['assignment_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('student', 'ta', 'instructor', name='role', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('active', 'dropped', name='enrollmentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('ta_sections', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'user_id', name='uq_enrollment')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_offering_id'), ['offering_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('qid', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('max_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('auto_points_max', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('grading_mode', sa.Enum('auto', 'manual', 'hybrid', name='gradingmode', native_enum=False, length=16), nullable=False),
    sa.Column('check_keys', sa.JSON(), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'qid', name='uq_question_qid')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_assignment_id'), ['assignment_id'], unique=False)

    op.create_table('check_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('check_key', sa.String(length=120), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_events_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_events_question_id'), ['question_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_version_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notebook_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('outputs_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('render_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('client_check_results', sa.JSON(), nullable=False),
    sa.Column('client_meta', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('received', 'grading', 'graded', 'failed', name='submissionstatus', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['assignment_version_id'], ['assignment_versions.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['notebook_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['outputs_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['render_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'question_id', 'attempt_no', name='uq_attempt')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_assignment_version_id'), ['assignment_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_question_id'), ['question_id'], unique=False)

    op.create_table('grader_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('autograde', 'render', 'ai_suggest', name='runkind', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='runstatus', native_enum=False, length=16), nullable=False),
    sa.Column('grader_version', sa.String(length=64), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log_artifact_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['log_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grader_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grader_runs_submission_id'), ['submission_id'], unique=False)

    op.create_table('question_grades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'question_id', name='uq_qgrade')
    )
    with op.batch_alter_table('question_grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_grades_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_grades_question_id'), ['question_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('auto_points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('manual_points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rubric_scores', sa.JSON(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('suggested_points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('suggested_feedback', sa.Text(), nullable=True),
    sa.Column('grader_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grader_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_submission_id'))

    op.drop_table('scores')
    with op.batch_alter_table('question_grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_grades_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_grades_enrollment_id'))

    op.drop_table('question_grades')
    with op.batch_alter_table('grader_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grader_runs_submission_id'))

    op.drop_table('grader_runs')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_question_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_assignment_version_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('check_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_events_question_id'))
        batch_op.drop_index(batch_op.f('ix_check_events_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_check_events_at'))

    op.drop_table('check_events')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_assignment_id'))

    op.drop_table('questions')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_user_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_offering_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('assignment_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_versions_assignment_id'))

    op.drop_table('assignment_versions')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_offering_id'))

    op.drop_table('sections')
    with op.batch_alter_table('rubrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubrics_offering_id'))

    op.drop_table('rubrics')
    with op.batch_alter_table('roster_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roster_uploads_offering_id'))

    op.drop_table('roster_uploads')
    with op.batch_alter_table('grade_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_audit_offering_id'))
        batch_op.drop_index(batch_op.f('ix_grade_audit_at'))

    op.drop_table('grade_audit')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_offering_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_web_sessions_expires_at'))

    op.drop_table('web_sessions')
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offerings_course_id'))

    op.drop_table('offerings')
    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_codes_user_code'))

    op.drop_table('device_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_netid'))

    op.drop_table('users')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    op.drop_table('courses')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_sha256'))

    op.drop_table('artifacts')
    # ### end Alembic commands ###
