"""client_submission_id

Revision ID: 71f30487b560
Revises: 78daee919109
Create Date: 2026-09-11 10:22:44.192928
"""
from alembic import op
import sqlalchemy as sa


revision = '71f30487b560'
down_revision = '78daee919109'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_submission_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_client_submission', ['enrollment_id', 'question_id', 'client_submission_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_client_submission', type_='unique')
        batch_op.drop_column('client_submission_id')

    # ### end Alembic commands ###
